config/routes.rb
Rails.application.routes.draw do

  resources :archives

  resources :send_queues do
		collection do 
			get :drops
		end
	end

  resources :templates do
    collection do
      get :login	
      post :check_login	
      get :beacons_service
      get :frame_welcome
    end
  end

end

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
		<%= f.label "Upload template" %><br>
		<%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :start_date_top %><br>
    <%= f.text_field :start_date_top %>
  </div>
  <div class="field">
    <%= f.label :start_date_left %><br>
    <%= f.text_field :start_date_left %>
  </div>
  <div class="field">
    <%= f.label :start_date_width %><br>
    <%= f.text_field :start_date_width %>
  </div>
  <div class="field">
    <%= f.label :start_date_height %><br>
    <%= f.text_field :start_date_height %>
  </div>
  <div class="field">
    <%= f.label :end_date_top %><br>
    <%= f.text_field :end_date_top %>
  </div>
  <div class="field">
    <%= f.label :end_date_left %><br>
    <%= f.text_field :end_date_left %>
  </div>
  <div class="field">
    <%= f.label :end_date_width %><br>
    <%= f.text_field :end_date_width %>
  </div>
  <div class="field">
    <%= f.label :end_date_height %><br>
    <%= f.text_field :end_date_height %>
  </div>
  <div class="field">
    <%= f.label :coupon_top %><br>
    <%= f.text_field :coupon_top %>
  </div>
  <div class="field">
    <%= f.label :coupon_left %><br>
    <%= f.text_field :coupon_left %>
  </div>
  <div class="field">
    <%= f.label :coupon_width %><br>
    <%= f.text_field :coupon_width %>
  </div>
  <div class="field">
    <%= f.label :coupon_height %><br>
    <%= f.text_field :coupon_height %>
  </div>
  <div class="field">
    <%= f.label :date_font_size %><br>
    <%= f.text_field :date_font_size %>
  </div>
  <div class="field">
    <%= f.label :date_font_color %><br>
    <%= f.text_field :date_font_color %>
  </div>
  <div class="field">
    <%= f.label :coupon_font_size %><br>
    <%= f.text_field :coupon_font_size %>
  </div>
  <div class="field">
    <%= f.label :coupon_font_color %><br>
    <%= f.text_field :coupon_font_color %>
  </div>
  <div class="field">
    <%= f.label :template_type %><br>
    <%= f.text_field :template_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/beacons_service.html.erb
<!DOCTYPE html PUBliC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8;"/>
		<title>蓝牙推送服务端</title>
		<link type="text/css" rel="stylesheet" href="/assets/index.css">
		<script type="text/javascript">
			function toggleHistoryUl(){
				if($('#newHistory').css("display") == "block"){
					$('#newHistory').css("display", "none");
				}else{
					$('#newHistory').css("display", "block");
				}
			}
		</script>
	</head>
	<body>
		<div id="titleDiv" class="titleLogo">
			<img src="/assets/img/logo.png" title="orange_star" />
			<div id="tilteRight">
				<span>用户名：</span><span><%= params[:user] %></span>
			</div>
		</div>
		<div id="contentDiv" class="contentCss">
			<div id="leftNav" >
				<ul>
					<li><a href="/templates" target="myFrame">模板广告</a></li>
					<li><a href="/send_queues/new" target="myFrame">自定义上传</a></li>
					<li>
						<a  onclick="toggleHistoryUl();">历史查询</a>
						<ul id='newHistory' style="display:none;">
							<li><a href="/send_queues?status=ok" target="myFrame">已发布</a></li>
							<li><a href="/send_queues?status=no" target="myFrame">未发布</a></li>
							<li><a href="/send_queues?status=pass" target="myFrame">已过期</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<div id="rightFrame" >
				<iframe src="/templates/frame_welcome" name="myFrame"  width=900 height=850 frameborder=0 scrolling=auto > </iframe>
			</div>
		</div>
	</body>
</html>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/frame_welcome.html.erb
<div id="contentDiv" class="contentCss">
	<div id="rightDiv">
		<center><h1>Hello , Welcome!!!</h1></center>
	</div>
</div>

app/views/templates/index.html.erb
<div class="demoDiv">
	<ul class="demoUl">
		<% @templates.each do |template| %>
		<li>
			<a href="/templates/<%= template.id %>" target="myFrame">
				<%=  image_tag template.image.url(:thumb) %>
				<p></p>
				<span> <%= template.template_type %> </span>
			</a>
		</li>
		<% end %>
	</ul>
</div>

app/views/templates/login.html.erb
<!DOCTYPE html PUBliC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8;"/>
		<title>蓝牙推送服务端</title>
		<script type="text/javascript" src="/assets/storage.js"></script>
		<script type="text/javascript" src="/assets/index.js"></script>
		<link type="text/css" rel="stylesheet" href="/assets/index.css">
	</head>
	<body>
		<div id="logo" class="titleLogo">
			<img src="/assets/img/logo.png" title="orange_star" />
		</div>
		<div id="logoDiv" class="logionDialog">
			<form action="check_login" method="post">
			<label for="user_name">用户名:</label>
			<input type="text" name="user_name" id="user_name" placeholder="登录帐号(用户名)";/><br />
			<label for="password">密　码:</label>
			<input type="password" name="password" id="password" /><br />
			<input type="submit" value="登录"/>
			</form>
		</div>
		<h4 style="color: red;  text-align: center;"><%= params[:notice]%></h4>
	</body>
</html>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<div class="editDemoDiv">
	<form class="editDemoForm" action="/send_queues" method="post">
		<input type="hidden" name="my_id" value="<%= @template.id %>">
		<%= image_tag @template.image.url(:medium) %>
		<input type="text" id="coupon" name="coupon"/>
		<div id="activitiesDate">
			<label for="start_date">活动日期:</label>
			<input type="date" id="start_date" name="start_date"/> -
			<input type="date" id="end_date" name="end_date"/>
		</div>
		<div class="summary">
			<label for="msg_summary">广告概述:</label>
			<input type="text" id="msg_summary" name="msg_summary"/>
		</div>
		<div id="releaseDate">
			<label for="release_start_date">发布日期:</label>
			<input type="date" id="release_start_date" name="release_start_date"/> -
			<input type="date" id="release_end_date" name="release_end_date"/>
		</div>
		<div class="beaconsID">
			允许的蓝牙基站号:
			<select name="beacon_id" id="beacon_id">
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
			</select>
		</div>
		<input type="submit"  id="draft" name="commit" value="草稿"/>
		<input type="submit"  id="release" name="commit" value="发布"/>
	</form>
</div>