config/routes.rb
Rails.application.routes.draw do

  resources :archives

  resources :send_queues do
		collection do 
			get :drops
		end
	end

  resources :templates do
    collection do
      get :login	
      post :check_login	
      get :beacons_service
      get :frame_welcome
    end
  end

end

app/models/archive.rb
require "securerandom"
class Archive < ActiveRecord::Base
	before_create :generate_uuid
  has_attached_file :image, :styles => { :larger => "480x800>", :medium => "320x533>", :thumb => "150x250>", :mini => "100x166>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  private
  def generate_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :edit, :update, :destroy]

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: 'Archive was successfully created.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: 'Archive was successfully updated.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: 'Archive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:uuid, :start_date_top, :start_date_left, :start_date_width, :start_date_height, :start_date, :end_date_top, :end_date_left, :end_date_width, :end_date_height, :end_date, :coupon_top, :coupon_left, :coupon_width, :coupon_height, :coupon, :date_font_size, :date_font_color, :coupon_font_size, :coupon_font_color, :release_start_date, :release_end_date, :send_time, :beacon_id)
    end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/_form.html.erb
<%= form_for(@archive) do |f| %>
  <% if @archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% @archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :start_date_top %><br>
    <%= f.text_field :start_date_top %>
  </div>
  <div class="field">
    <%= f.label :start_date_left %><br>
    <%= f.text_field :start_date_left %>
  </div>
  <div class="field">
    <%= f.label :start_date_width %><br>
    <%= f.text_field :start_date_width %>
  </div>
  <div class="field">
    <%= f.label :start_date_height %><br>
    <%= f.text_field :start_date_height %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date_top %><br>
    <%= f.text_field :end_date_top %>
  </div>
  <div class="field">
    <%= f.label :end_date_left %><br>
    <%= f.text_field :end_date_left %>
  </div>
  <div class="field">
    <%= f.label :end_date_width %><br>
    <%= f.text_field :end_date_width %>
  </div>
  <div class="field">
    <%= f.label :end_date_height %><br>
    <%= f.text_field :end_date_height %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :coupon_top %><br>
    <%= f.text_field :coupon_top %>
  </div>
  <div class="field">
    <%= f.label :coupon_left %><br>
    <%= f.text_field :coupon_left %>
  </div>
  <div class="field">
    <%= f.label :coupon_width %><br>
    <%= f.text_field :coupon_width %>
  </div>
  <div class="field">
    <%= f.label :coupon_height %><br>
    <%= f.text_field :coupon_height %>
  </div>
  <div class="field">
    <%= f.label :coupon %><br>
    <%= f.number_field :coupon %>
  </div>
  <div class="field">
    <%= f.label :date_font_size %><br>
    <%= f.text_field :date_font_size %>
  </div>
  <div class="field">
    <%= f.label :date_font_color %><br>
    <%= f.text_field :date_font_color %>
  </div>
  <div class="field">
    <%= f.label :coupon_font_size %><br>
    <%= f.text_field :coupon_font_size %>
  </div>
  <div class="field">
    <%= f.label :coupon_font_color %><br>
    <%= f.text_field :coupon_font_color %>
  </div>
  <div class="field">
    <%= f.label :release_start_date %><br>
    <%= f.date_select :release_start_date %>
  </div>
  <div class="field">
    <%= f.label :release_end_date %><br>
    <%= f.date_select :release_end_date %>
  </div>
  <div class="field">
    <%= f.label :send_time %><br>
    <%= f.datetime_select :send_time %>
  </div>
  <div class="field">
    <%= f.label :beacon_id %><br>
    <%= f.text_field :beacon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h1>Editing archive</h1>

<%= render 'form' %>

<%= link_to 'Show', @archive %> |
<%= link_to 'Back', archives_path %>

app/views/archives/index.html.erb
<h1>Listing archives</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Start date top</th>
      <th>Start date left</th>
      <th>Start date width</th>
      <th>Start date height</th>
      <th>Start date</th>
      <th>End date top</th>
      <th>End date left</th>
      <th>End date width</th>
      <th>End date height</th>
      <th>End date</th>
      <th>Coupon top</th>
      <th>Coupon left</th>
      <th>Coupon width</th>
      <th>Coupon height</th>
      <th>Coupon</th>
      <th>Date font size</th>
      <th>Date font color</th>
      <th>Coupon font size</th>
      <th>Coupon font color</th>
      <th>Release start date</th>
      <th>Release end date</th>
      <th>Send time</th>
      <th>Beacon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= archive.uuid %></td>
        <td><%= archive.start_date_top %></td>
        <td><%= archive.start_date_left %></td>
        <td><%= archive.start_date_width %></td>
        <td><%= archive.start_date_height %></td>
        <td><%= archive.start_date %></td>
        <td><%= archive.end_date_top %></td>
        <td><%= archive.end_date_left %></td>
        <td><%= archive.end_date_width %></td>
        <td><%= archive.end_date_height %></td>
        <td><%= archive.end_date %></td>
        <td><%= archive.coupon_top %></td>
        <td><%= archive.coupon_left %></td>
        <td><%= archive.coupon_width %></td>
        <td><%= archive.coupon_height %></td>
        <td><%= archive.coupon %></td>
        <td><%= archive.date_font_size %></td>
        <td><%= archive.date_font_color %></td>
        <td><%= archive.coupon_font_size %></td>
        <td><%= archive.coupon_font_color %></td>
        <td><%= archive.release_start_date %></td>
        <td><%= archive.release_end_date %></td>
        <td><%= archive.send_time %></td>
        <td><%= archive.beacon_id %></td>
        <td><%= link_to 'Show', archive %></td>
        <td><%= link_to 'Edit', edit_archive_path(archive) %></td>
        <td><%= link_to 'Destroy', archive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archive', new_archive_path %>

app/views/archives/new.html.erb
<h1>New archive</h1>

<%= render 'form' %>

<%= link_to 'Back', archives_path %>

app/views/archives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @archive.uuid %>
</p>

<p>
  <strong>Start date top:</strong>
  <%= @archive.start_date_top %>
</p>

<p>
  <strong>Start date left:</strong>
  <%= @archive.start_date_left %>
</p>

<p>
  <strong>Start date width:</strong>
  <%= @archive.start_date_width %>
</p>

<p>
  <strong>Start date height:</strong>
  <%= @archive.start_date_height %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @archive.start_date %>
</p>

<p>
  <strong>End date top:</strong>
  <%= @archive.end_date_top %>
</p>

<p>
  <strong>End date left:</strong>
  <%= @archive.end_date_left %>
</p>

<p>
  <strong>End date width:</strong>
  <%= @archive.end_date_width %>
</p>

<p>
  <strong>End date height:</strong>
  <%= @archive.end_date_height %>
</p>

<p>
  <strong>End date:</strong>
  <%= @archive.end_date %>
</p>

<p>
  <strong>Coupon top:</strong>
  <%= @archive.coupon_top %>
</p>

<p>
  <strong>Coupon left:</strong>
  <%= @archive.coupon_left %>
</p>

<p>
  <strong>Coupon width:</strong>
  <%= @archive.coupon_width %>
</p>

<p>
  <strong>Coupon height:</strong>
  <%= @archive.coupon_height %>
</p>

<p>
  <strong>Coupon:</strong>
  <%= @archive.coupon %>
</p>

<p>
  <strong>Date font size:</strong>
  <%= @archive.date_font_size %>
</p>

<p>
  <strong>Date font color:</strong>
  <%= @archive.date_font_color %>
</p>

<p>
  <strong>Coupon font size:</strong>
  <%= @archive.coupon_font_size %>
</p>

<p>
  <strong>Coupon font color:</strong>
  <%= @archive.coupon_font_color %>
</p>

<p>
  <strong>Release start date:</strong>
  <%= @archive.release_start_date %>
</p>

<p>
  <strong>Release end date:</strong>
  <%= @archive.release_end_date %>
</p>

<p>
  <strong>Send time:</strong>
  <%= @archive.send_time %>
</p>

<p>
  <strong>Beacon:</strong>
  <%= @archive.beacon_id %>
</p>

<%= link_to 'Edit', edit_archive_path(@archive) %> |
<%= link_to 'Back', archives_path %>